# Generated by Django 3.0.8 on 2020-10-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20201019_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='snippet',
            field=models.CharField(default='Click here to read more...', max_length=200),
        ),
    ]
