# Generated by Django 3.0.8 on 2020-10-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='snippet',
            field=models.CharField(max_length=200),
        ),
    ]
